# -*- coding: utf-8 -*-
"""AI_Sprint_quiz_modual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voLEQPku2rJuJrV9NE8iWKBxgSG1Ufqz
"""

pip install chromadb

import os
import glob
import json
import chromadb
from pydantic import BaseModel

# --- [데이터 스키마 (Pydantic)] ---
class Prerequisite(BaseModel):
    name: str
    chapter: str | None = None
    depth: int = 1

class QuizItem(BaseModel):
    quiz_id: str          # 채점할 때 매칭용 
    question: str
    answer: str           # 정답 
    concept: str          # 어떤 개념 확인용인지

class GradeResult(BaseModel):
    quiz_id: str
    is_correct: bool
    feedback: str

class TraceState(BaseModel):
    question: str
    concepts: list[str] = []
    prerequisites: list[Prerequisite] = []
    selected: list[str] = []
    explanation: str = ""
    quiz: list[QuizItem] = []
    user_answers: dict[str, str] = {}    # {quiz_id: 학생 답}
    grade_results: list[GradeResult] = []


# --- [1. DB 연결] ---
DB_PATH = "data/chromadb/chroma.sqlite3"
client = chromadb.PersistentClient(path=DB_PATH)
collection = client.get_or_create_collection(
    name="problem_collection"
)

"""
# --- [2. (선택) 만약 DB 구축이 안 되어있을 때 JSON 데이터를 적재하는 함수] ---
DATA_PATH = "/content/drive/MyDrive/Training"

def load_real_data_to_chroma(data_path: str):
    json_files = glob.glob(os.path.join(data_path, "**/*.json"), recursive=True)

    if not json_files:
        print("경로에 JSON 파일이 없습니다.")
        return

    print(f"총 {len(json_files)}개의 데이터 파일을 읽어옵니다...")

    docs = []
    metas = []
    ids = []

    for idx, file_path in enumerate(json_files):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                j_data = json.load(f)

            # JSON 내부에 고유 ID가 있으면 꺼내고, 없으면 fallback으로 생성
            real_quiz_id = str(j_data.get("quiz_id") or j_data.get("id") or f"quiz_{idx:05d}")
            question_text = j_data.get("question", "")
            answer_text = j_data.get("answer", "정답없음")
            concept_text = j_data.get("concept", "일반")

            if question_text:
                docs.append(question_text)
                metas.append({
                    "answer": str(answer_text),
                    "concept": str(concept_text)
                })
                ids.append(real_quiz_id)  # 채점 매칭을 위해 필수 저장
        except Exception as e:
            continue

    if docs:
        collection.upsert(
            documents=docs,
            metadatas=metas,
            ids=ids
        )
        print(f"성공적으로 {len(docs)}개의 진짜 데이터가 DB에 적재되었습니다")

# ※ 이미 chromadb 데이터를 생성해 둔 상태라면 아래 호출문은 주석 처리
try:
    load_real_data_to_chroma(DATA_PATH)
except Exception as e:
    print("데이터 적재 중 알림 (이미 DB가 존재하는 경우 무시 가능):", e)
"""

# --- [3. 핵심 검색 함수 (TraceState 규격과 연동)] ---
def get_quiz_from_chroma(data: dict) -> dict:
    """
    팀원들과 약속한 input (data) 예시:
    {"selected": ["일차함수", "이차함수"]}

    반환 형태:
    {"quiz": [QuizItem, QuizItem, ...]}
    """
    selected_concepts = data.get("selected", [])
    quiz_list: list[QuizItem] = []

    for concept in selected_concepts:
        # DB에서 선택된 개념 키워드로 유사 문제 2개씩 검색
        results = collection.query(
            query_texts=[concept],
            n_results=2
        )

        documents = results.get('documents', [[]])[0]
        ids = results.get('ids', [[]])[0]
        metadatas = results.get('metadatas', [[]])[0]

        for i in range(len(documents)):
            meta = metadatas[i] if i < len(metadatas) else {}

            # 핵심: 약속된 QuizItem 스키마에 정확히 매칭해서 생성
            quiz_item = QuizItem(
                quiz_id=ids[i] if i < len(ids) else f"q_{i}",  # 채점용 ID
                question=documents[i],
                answer=meta.get("answer", "정답없음"),
                concept=meta.get("concept", concept)
            )
            quiz_list.append(quiz_item)

    return {"quiz": quiz_list}


# --- [4. 실행 및 검증] ---
if __name__ == "__main__":
    # TraceState의 selected 필드처럼 개념 전달
    test_input = {"selected": ["일차함수"]}

    result = get_quiz_from_chroma(test_input)
    print("\n--- 최종 검색 결과 (QuizItem 스키마 적용) ---")
    print(result)
