# -*- coding: utf-8 -*-
"""AI_Sprint_Week1_OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WOI81MYt1USI9IjMpM7fcp9AB9S7OQm
"""

!pip install google-genai

# 1. 나눔 폰트 설치
!apt-get update -qq
!apt-get install fonts-nanum* -qq

# 2. 폰트 매니저에 폰트 추가
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt

# 나눔 폰트 리스트 확인 및 적용
font_list = fm.findSystemFonts(fontpaths=['/usr/share/fonts/truetype/nanum/'])
for f in font_list:
    fm.fontManager.addfont(f)

# 3. 폰트 설정 적용 (나눔고딕으로 설정)
plt.rc('font', family='NanumGothic')

# 4. (필수) 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

print("한글 폰트 설정 완료. 이제 코랩을 다시 실행.")

import requests
import base64
import matplotlib.pyplot as plt
from google.colab import userdata

# 1. 설정
api_key = userdata.get('GEMINI_API_KEY')
image_path = '/content/sample_data/1.png'
model_name = 'gemini-3.5-flash'
url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"

# 2. 이미지 Base64 인코딩
with open(image_path, "rb") as image_file:
    encoded_string = base64.b64encode(image_file.read()).decode('utf-8')

# 3. 요청 및 렌더링
prompt = r"""당신은 20년 경력의 친절하고 인내심 많은 수학 과외선생님입니다.
학생이 스스로 이해하도록 돕는 것이 목표이며, 답만 알려주지 않습니다.

[규칙]
1.	풀이단계를 세우고, 각 단계에 필요한 개념을 뽑음
2.	우선 첫번째 단계만을 풀기위한 방향만 제시해줌 (예시: 접선의 방정식을 구하는 문제라면, “기울기를 먼저 찾아보세요”처럼 제시해줌


이제 아래 문제를 위 방식대로 풀어주세요."""
payload = {
    "contents": [{"parts": [
        {"text": prompt},
        {"inline_data": {"mime_type": "image/png", "data": encoded_string}}
    ]}]
}

response = requests.post(url, json=payload)

if response.status_code == 200:
    latex_text = response.json()['candidates'][0]['content']['parts'][0]['text']
    print(f"✨ 추출 결과: {latex_text}")

    # 렌더링 (에러 방지)
    try:
        # $ 기호가 포함되어 있으면 제거하고 깔끔하게 렌더링
        clean_text = latex_text.replace('$', '').strip()
        fig = plt.figure(figsize=(8, 2))
        plt.text(0.5, 0.5, f"${clean_text}$", fontsize=20, ha='center', va='center')
        plt.axis('off')
        plt.show()
    except Exception as e:
        print(f"렌더링 실패: {e}")
else:
    print(f"에러 발생: {response.text}")